title: Ella Reiter
defaults:
  - scope:
      path: "" # empty string applies to all files
    values:
      image: /Users/ellareiter/Desktop/Ella's Stuff/Career:Internships/IMG_6388.jpg
theme: jekyll-theme-minimal
